#Example Configuration
uecode_qpush:
    cache_service: null
    logging_enabled: true
    providers:
        aws:
            key:
            secret:
            region:
        ironmq:
            token:
            project_id:
            host:
    queues:
        default:
            provider: aws #or ironmq
            options:
                push_notifications:     true
                notification_retries:   3
                message_delay:          0
                message_timeout:        30
                message_expiration:     604800
                messages_to_receive:    1
                receive_wait_time:      3
                subscribers:
                    - { endpoint: http://example1.com/qpush, protocol: http }
                    - { endpoint: http://example2.com/qpush, protocol: http }

doctrine:
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                # Match agains should have the path to the MatchAgainst class created in the previous step
                MATCH_AGAINST: qpush-bundle\Extensions\Doctrine\MatchAgainst