services:
    ### QPush Registry
    uecode_qpush.registry:
        class: '%uecode_qpush.registry.class%'
    uecode_qpush:
        alias: uecode_qpush.registry

    ### QPush Default File Cache
    uecode_qpush.file_cache:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments: ['%kernel.cache_dir%/qpush', qpush.php]
        public: false
      
    Uecode\Bundle\QPushBundle\Command\:
        resource: '../../Command'
        
    Uecode\Bundle\QPushBundle\Provider\ProviderRegistry: '@uecode_qpush.registry'   
