services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    ### QPush Registry
    uecode_qpush.registry:
        class: '%uecode_qpush.registry.class%'
    uecode_qpush:
        alias: uecode_qpush.registry

    ### QPush Default File Cache
    uecode_qpush.file_cache:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments: ['%kernel.cache_dir%/qpush', qpush.php]
        public: false
      
    Uecode\Bundle\QPushBundle\Command\:
        resource: '../../Command'
        tags: ['console.command']

    Uecode\Bundle\QPushBundle\Provider\ProviderRegistry: '@uecode_qpush.registry'   
    
    Uecode\Bundle\QPushBundle\Repository\:
        resource: '../../Repository'